tutoWelcomeBundle_homepage:
    pattern:  /
    defaults: { _controller: tutoWelcomeBundle:Homepage:index }

tutoWelcomeBundle_whoami:
    pattern:  /qui-suis-je/{name}
    defaults: { _controller: tutoWelcomeBundle:Homepage:whoAmI }
    requirements:
      name: \w+